name: 'DevOps CI Pipeline'

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  terraform-k8s-validation:
    name: 'Validate IaC and K8s Manifests'
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do repositório no servidor do GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Instala e configura o Terraform para o teste
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    # 3. Valida a sintaxe do Terraform
    - name: Terraform Init & Validate
      run: |
        cd terraform
        terraform init -backend=false
        terraform validate

   # 4. Valida se os manifestos estruturais do Kubernetes estão corretos
    - name: Validate Kubernetes Manifests
      run: |
        sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl chmod +x /usr/local/bin/kubectl
        # Validação de sintaxe pura de todos os arquivos sem frescura de espaços
        find k8s/ -name "*.yaml" -type f -exec kubectl patch -f {} --local -p '{}' \;